version: "3.8"
services:
  poe:
    build: .
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
