version: "3.8"
services:
  poe:
    build: .
    ports:
      - "${FLASK_APP_PORT}:${FLASK_APP_PORT}"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "${DB_PORT}:{DB_PORT}"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
